const IMAGES = {
  facebook: require("../img/001-facebook.png"),
  twitter: require("../img/003-twitter.png"),
  instagram: require("../img/004.png"),
  micro_interface: require("../img/micro.png"),
  logo: require("../img/logo.png"),
  brand: require("../img/brand.png"),
  career: require("../img/career.png"),
  noon: require("../img/noon.png"),
  phone: require("../img/phone.png"),
  aside: require("../img/aside.jpg"),
  hundred: require("../img/100.png"),
  smile: require("../img/smile.png"),
  star: require("../img/star.jpg"),
  num1: require("../img/num1.png"),
  num2: require("../img/num2.png"),
  num3: require("../img/num3.png"),
  num4: require("../img/num4.png"),
  mans: require("../img/mans.png"),
  desicion: require("../img/desicion.png"),
  meets: require("../img/meet.png"),
  nicePhone: require("../img/nicePhone.png"),
  man: require("../img/man.png"),
  screen: require("../img/screen.png"),
  manage: require("../img/manage.png"),
  arrow: require("../img/arrow.png"),
  location: require("../img/location.png"),
  email: require("../img/email.png"),
  call: require("../img/call.png"),
  girl_light: require("../img/girl_light.png"),
  man_dark: require("../img/man_dark.png"),
  glass_dark: require("../img/glass_dark.png"),
  pluse: require("../img/plus.png"),
  Frame: require("../img/Frame.png"),
  girlwithhear: require("../img/girlwithhear.png"),
  gentaleman: require("../img/gentaleman.png"),
  girlpersone: require("../img/girl-persone.png"),
  heyman: require("../img/hey-man.png"),
};

export default IMAGES;
